name: CI

env:
  QT_VERSION:     "5.13.0"
  MINGW_VERSION:  "win64_mingw73"
  MINGW_PATH:     "mingw73_64"
  PLUGIN_PRO: CocktailCalc.pro
  PLUGIN_NAME: CocktailCalc
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Windows Latest x64",
            artifact: "Windows-x64.zip",
            os: windows-latest,
            host: windows,
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        - {
            name: "Linux Latest x64",
            artifact: "Linux-x64.zip",
            os: ubuntu-latest,
            host: linux
          }

    steps:
      - name: Print working directory on runner
        run: echo "${GITHUB_WORKSPACE}"

      - uses: actions/checkout@v2
      
      - name: Installing system libs
        shell: cmake -P {0}
        run: |
          if ("${{ runner.os }}" STREQUAL "Linux")
            execute_process(
              COMMAND sudo apt install libgl1-mesa-dev
            )
          endif()
          
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
    
      - name: Install Qt Windows
        if: startsWith(matrix.config.os, 'windows')
        uses: jurplel/install-qt-action@v2
        with:
          host: ${{ matrix.config.host }}
          version: ${{ env.QT_VERSION }}
          arch: ${{ env.MINGW_VERSION }}
          extra: --external 7z
    
      - name: Install Qt Ubuntu
        if: (!startsWith(matrix.config.os, 'windows'))
        uses: jurplel/install-qt-action@v2
        with:
          host: ${{ matrix.config.host }}
          version: ${{ env.QT_VERSION }}
          extra: --external 7z
  
      - name: Qmake Windows
        if: startsWith(matrix.config.os, 'windows')
        env:
          QT_VERSION: ${{ env.QT_VERSION }}
        run: |
          qmake CocktailCalc.pro -spec win32-g++ "CONFIG+=release" QTC_SOURCE="${qtcreator_dir}" QTC_BUILD="${qtcreator_dir}" #"LIBS += ${GITHUB_WORKSPACE}\Qt\${{ env.QT_VERSION }}/${{ env.MINGW_PATH }}\lib\libQt5Cored.a"
      
      - name: Qmake Ubuntu
        if: (!startsWith(matrix.config.os, 'windows'))
        env:
          QT_VERSION: ${{ env.QT_VERSION }}
        run: |
          qmake CocktailCalc.pro "CONFIG+=release" QTC_SOURCE="${qtcreator_dir}" QTC_BUILD="${qtcreator_dir}"
          make qmake_all

      - name: Build
        env:
          QT_VERSION: ${{ matrix.version }}
        run: |
          make

      - name: upload artifact release
        uses: actions/upload-artifact@v3
        with:
          path: ./${{ env.PLUGIN_NAME }}-${{ env.QT_CREATOR_VERSION }}-${{ matrix.config.artifact }}
          name: ${{ env.PLUGIN_NAME}}-${{ env.QT_CREATOR_VERSION }}-${{ matrix.config.artifact }}
